version: '3.8'

services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile.prod
      context: ./nginx
    tty: true
    environment:
      - NODE_ENV=production
    volumes: 
    # - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount Nginx configuration file
    - ./frontend/build:/usr/share/nginx/html # Mount the dist directory containing production code
    # - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf # Mount custom Nginx configuration
    networks:
        - appcode-net
    ports:
      - "80:80"
      - "443:443"
  backend:
    image: backend:1.0.0
    container_name: backend
    working_dir: /app
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
        - "8000:8000"
    networks:
      - appcode-net
    volumes:
      - ./backend/dist:/app/dist
    tty: true
    environment:
      - NODE_ENV=production
    stdin_open: true
    command: npm run start
    
  frontend:
    image: frontend:1.0.0
    container_name: frontend
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
        - appcode-net
    volumes:
      - ./frontend/build:/app/build
    tty: true
    environment:
      - NODE_ENV=production
    stdin_open: true
    command: npm run start
networks:
    appcode-net:
        driver: bridge
