name: Deploy Application

on:
  push:
    branches:
      - main
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build frontend Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest ./frontend
      
    - name: Push frontend Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

  build_backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build backend Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:latest ./backend
      
    - name: Push backend Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

  deploy:
    runs-on: ubuntu-latest

    needs: [build_frontend, build_backend]
    
    steps:
    - name: Deploy to server
      run: |
        ssh ubuntu@ip-172-26-15-22 'docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest && docker pull ${{ secrets.DOCKER_USERNAME }}/backend-app:latest && docker-compose -f /../../docker-compose-prod.yml up -d'
