name: Deploy Application

on:
  push:
    branches:
      - main
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jjobs: 
  Build:
    runs-on: self-hosted 
     
    steps: 
      - uses: actions/checkout@main 
      - name: Run build 
        run: docker-compose -f docker-compose-prod.yml up -d
